# syntax=docker/dockerfile:1.2
FROM ubuntu:20.04

# This is the Python version that we install. Deadsnakes PPA wants MAJOR.MINOR.
ARG PYTHON_VERSION=3.7

# Set frontend to non-interactive time zone setup does not ask questions
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles
ENV POETRY_VERSION=1.1.6
ENV TVM_HOME="/usr/tvm"
ENV PYTHONPATH=${TVM_HOME}"/python"
ENV PATH="/root/.poetry/bin:${TVM_HOME}/build:$PATH"

RUN apt-get update

RUN apt-get install -y \
            apt-utils \
            build-essential \
            clang-11 \
            cmake \
            curl \
            git \
            libopenblas-dev \
            protobuf-compiler \
            python3-pip \
            vim

    # Install ${PYTHON_VERSION} from Deadsnakes PPA, and set python/pip aliases.
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y \
        "python${PYTHON_VERSION}" \
        "python${PYTHON_VERSION}-dev" \
        "python${PYTHON_VERSION}-venv" && \
    update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/${POETRY_VERSION}/get-poetry.py | python - && \
    poetry config virtualenvs.create false

# Install just
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --tag v0.9.2 --to /usr/local/bin

WORKDIR ${TVM_ROOT}

COPY pyproject.toml poetry.lock ${TVM_HOME}}/
RUN poetry install --no-interaction --no-ansi

COPY . ${TVM_HOME}/
RUN ${TVM_HOME}/docker/build_dev.sh

COPY . ${HULK_ROOT}
